CollectionManager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('collectionsapp.urls')),    # bound project to collections url
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collectionsapp/urls.py
from django.urls import path
from . import views

app_name = 'collections'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /collections/5/
    path('<int:collection_id>/', views.detail, name='detail'),
    path('<int:collection_id>/delete_collection/', views.delete_collection, name='delete_collection'),
    path('<int:collection_id>/edit_collection/', views.edit_collection, name='edit_collection'),
    path('<int:collection_id>/create_item/', views.create_item, name='create_item'),
    path('create_collection/', views.create_collection, name='create_collection'),
    # ex: /register/
    path('register/', views.register, name='register'),
    # ex: /login/
    path('login/', views.login_user, name='login'),
    # ex: /logout/
    path('logout/', views.logout_user, name='logout'),
    path('item/<int:value_id>/', views.item, name='item'),
    path('item/<int:value_id>/delete_item/', views.delete_item, name='delete_item'),
    path('item/<int:value_id>/edit_item/', views.edit_item, name='edit_item'),
]

collectionsapp/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Collection(models.Model):
    user = models.ForeignKey(User, default=1, verbose_name='Właściciel', on_delete=models.CASCADE)
    name = models.CharField('Nazwa', max_length=200)
    created = models.DateField('Data utworzenia', default=timezone.now)
    desc = models.CharField('Opis', max_length=1000)
    collection_logo = models.FileField(null=True, blank=True)

    def __str__(self):
        return "%s: %s" % (self.name, self.desc)

    def is_recently_created(self):
        # collection is considered recently created when its no older than 2 weeks
        return self.created >= timezone.now().date() - datetime.timedelta(weeks=2)

    def get_short_desc(self):
        return self.desc[:250] + "..."


class CollectionValue(models.Model):
    name = models.CharField('Nazwa', max_length=200)
    aggregate = models.CharField('Agregat (np. autor, zespół)', max_length=200)
    added = models.DateField('Data dodania', default=timezone.now)
    date = models.DateField('Data produkcji przedmiotu, np. data wydania książki, rocznik wina itd.')
    desc = models.CharField('Opis przedmiotu', max_length=2000)
    collection_id = models.ForeignKey(Collection, on_delete=models.CASCADE, verbose_name='Kolekcja')
    collectionValue_logo = models.FileField(null=True, blank=True)

    def __str__(self):
        return "%s \"%s\" (%s)" % (self.aggregate, self.name, self.date)

    def is_new_item(self):
        # item is considered new when it was added no longer than 30 days ago
        return self.added >= timezone.now().date() - datetime.timedelta(days=30)

    def get_short_desc(self):
        return self.desc[:250] + "..."

collectionsapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserForm(forms.ModelForm):
    username = forms.CharField(min_length=6, max_length=30, required=True, label="Nazwa użytkownika")
    first_name = forms.CharField(min_length=2, max_length=30, required=True, label="Imię")
    last_name = forms.CharField(min_length=2, max_length=50, required=True, label="Nazwisko")
    email = forms.EmailField(required=True, label="Email")
    password = forms.CharField(min_length=8, max_length=24, required=True, widget=forms.PasswordInput, label="Hasło")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


class CollectionForm(forms.ModelForm):
    name = forms.CharField(min_length=1, max_length=150, required=True, label="Nazwa kolekcji")
    desc = forms.CharField(min_length=1, max_length=900, required=True, label="Opis kolekcji", widget=forms.Textarea())
    collection_logo = forms.FileField(label="Zdjęcie kolekcji", required=False)

    class Meta:
        model = Collection
        fields = ('name', 'collection_logo', 'desc')


class ItemForm(forms.ModelForm):
    name = forms.CharField(min_length=1, max_length=150, required=True, label="Nazwa przedmiotu")
    desc = forms.CharField(min_length=1, max_length=1900, required=True, label="Opis przedmiotu", widget=forms.Textarea())
    aggregate = forms.CharField(min_length=1, max_length=150, required=True, label="Agregat")
    date = forms.CharField(label="Data utworzenia", required=True, widget=forms.TextInput(attrs={'placeholder':'YYYY-MM-DD'}))
    collectionValue_logo = forms.FileField(label="Zdjęcie kolekcji", required=False)

    class Meta:
        model = CollectionValue
        fields = ('name', 'aggregate', 'date', 'collectionValue_logo','desc')

collectionsapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect

from .forms import *
from django.db.models import Q

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('collections:login')
    else:
        return redirect('/')


def login_user(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            return redirect('/')
        else:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/')  # redirect to index
                else:
                    return render(request, 'collections/login.html',
                                  {'error_message': 'Twoje konto zostało zablokowane'})
            else:
                return render(request, 'collections/login.html',
                              {'error_message': 'Podany login lub hasło są niepoprawne'})
    return render(request, 'collections/login.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('collections:index')
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('collections:index')
    return render(request, 'collections/register.html', {"form": form})


def index(request):
    collections = Collection.objects.all()
    query = request.GET.get("q")
    if query:
        collections = collections.filter(Q(name__icontains=query) | Q(desc__icontains=query) |
                                         Q(created__icontains=query)).distinct()
    return render(request, 'collections/index.html', {'collections': collections})


def detail(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)
    collection_items = CollectionValue.objects.filter(collection_id=collection_id)
    query = request.GET.get("q")
    if query:
        collection_items = collection_items.filter(Q(name__icontains=query) | Q(desc__icontains=query) |
                                                   Q(aggregate__icontains=query) | Q(added__icontains=query) |
                                                   Q(date__icontains=query)).distinct()
    context = {
        'collection': collection,
        'collection_items': collection_items
    }
    return render(request, 'collections/detail.html', context)


def create_collection(request):
    if not request.user.is_authenticated:
        return redirect('collections:login')
    form = CollectionForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        collection = form.save(commit=False)
        collection.user = request.user
        collection.collection_logo = request.FILES.get('collection_logo', None)
        if collection.collection_logo:
            file_type = collection.collection_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'collection': collection,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'collections/create_collection.html', context)
        collection.save()
        return redirect('collections:detail', collection_id=collection.pk)
    return render(request, 'collections/create_collection.html', {"form": form})


def delete_collection(request, collection_id):
    if request.user.is_authenticated:
        if request.method == "POST":
            collection = Collection.objects.get(pk=collection_id)
            if request.user == collection.user:
                collection.delete()
    return redirect("collections:index")


def edit_collection(request, collection_id):
    if not request.user.is_authenticated:
        return redirect('collections:login')

    collection = get_object_or_404(Collection, pk=collection_id)
    if not request.user == collection.user:
        return redirect('collections:index')

    form = CollectionForm(request.POST or None, request.FILES or None, instance=collection)
    if form.is_valid():
        collection = form.save(commit=False)
        collection.collection_logo = request.FILES.get('collection_logo', None, )
        if collection.collection_logo:
            file_type = collection.collection_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'collection': collection,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'collections/edit_collection.html', context)
        collection.save()
        return redirect('collections:detail', collection_id=collection.pk)
    return render(request, 'collections/edit_collection.html', {"form": form})


def item(request, value_id):
    collection_value = get_object_or_404(CollectionValue, pk=value_id)
    context = {'value': collection_value}
    return render(request, 'collections/item.html', context)


def create_item(request, collection_id):
    if not request.user.is_authenticated:
        return redirect('collections:login')

    collection = get_object_or_404(Collection, pk=collection_id)
    if not request.user == collection.user:
        return redirect('collections:detail', collection_id=collection_id)

    form = ItemForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        collection_item = form.save(commit=False)
        collection_item.collection_id = collection
        collection_item.collectionValue_logo = request.FILES.get('collectionValue_logo', None)
        if collection_item.collectionValue_logo:
            file_type = collection_item.collectionValue_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'collection_item': collection_item,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'collections/create_item.html', context)
        collection_item.save()
        return redirect('collections:item', value_id=collection_item.id)
    return render(request, 'collections/create_item.html', {"form": form})


def delete_item(request, value_id):
    collection_item = CollectionValue.objects.get(pk=value_id)
    collection_id = collection_item.collection_id.pk

    if request.user.is_authenticated:
        if request.user == collection_item.collection_id.user:
            if request.method == "POST":
                collection_item.delete()
    return redirect("collections:detail", collection_id=collection_id)


def edit_item(request, value_id):
    collection_item = get_object_or_404(CollectionValue, pk=value_id)

    if not request.user.is_authenticated or not request.user == collection_item.collection_id.user:
        return redirect("collections:detail", collection_id=collection_item.collection_id.pk)

    form = ItemForm(request.POST or None, request.FILES or None, instance=collection_item)
    if form.is_valid():
        collection_item = form.save(commit=False)
        collection_item.collectionValue_logo = request.FILES.get('collectionValue_logo', None)
        if collection_item.collectionValue_logo:
            file_type = collection_item.collectionValue_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'collection_item': collection_item,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'collections/edit_item.html', context)
        collection_item.save()
        return redirect('collections:item', value_id=collection_item.pk)
    return render(request, 'collections/edit_item.html', {"form": form})

collectionsapp/templates/collections/create_collection.html
{% extends 'collections/header.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Dodaj nową kolekcję</h3>
                        {% if error_message %}
                            <div class="alert alert-danger" role="alert">
                                {{ error_message }}
                            </div>
                        {% endif %}
                        <form class="form-horizontal get-away" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'collections/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button class="btn btn-sm btn-primary" onClick="javascript:history.go(-1);">
                                        <i class="fas fa-chevron-left"></i>&nbsp;Powrót do listy kolekcji
                                    </button>
                                    <button type="submit" class="btn btn-sm btn-success"><i class="fas fa-save"></i>&nbsp;Dodaj</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

collectionsapp/templates/collections/detail.html
{% extends "collections/header.html" %}

{% block search %}
    <form class="form-inline" role="search" method="get" action="{% url 'collections:detail' collection.id %}">
        <div class="form-group">
            <input class="form-control mr-sm-2" type="search" placeholder="Szukaj przedmiotu" aria-label="Search" name="q" value="{{ request.GET.q }}">
        </div>
        <button type="submit" class="btn btn-sm btn-light"><i class="fas fa-search"></i></button>
    </form>
{% endblock %}

{% block content %}
    <div class="w3-panel w3-leftbar w3-border-blue">
        <div class="d-flex justify-content-between">
            <a href="{% url 'collections:detail' collection.id %}">
                {% if collection.collection_logo %}
                    <img class="image-size" src="{{ collection.collection_logo.url }}">
                {% endif %}
                <div class="col-sm8">
                    <h3>{{ collection.name }}</h3>
                </div>

            </a>
        </div>
        <small>Dodano {{ collection.created }} przez {{ collection.user.first_name }} {{ collection.user.last_name }}</small>
    </div>

    <div class="w3-panel w3-border w3-round">
        <h6>{{ collection.desc }}</h6>
    </div>

    <div class="col-sm4 get-away">
        <div class="form-inline btn-group" role="group">
            <a class="btn btn-sm btn-primary" href="{% url 'collections:index' %}">
                <i class="fas fa-chevron-left"></i>&nbsp;Powrót do listy
            </a>
            {% if user == collection.user %}
                <a class="btn btn-sm btn-warning" href="{% url 'collections:edit_collection' collection.id %}">
                    <i class="fas fa-edit"></i>&nbsp;Edytuj
                </a>
                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteConfirmation">
                    <i class="fas fa-trash-alt"></i>&nbsp;Usuń
                </button>
                <a class="btn btn-sm btn-success" href="{% url 'collections:create_item' collection.id %}">
                    <i class="fas fa-plus"></i>&nbsp;Dodaj przedmiot
                </a>
            {% endif %}
        </div>
    </div>

    <ul class="list-group get-away">
        <div class="get-away">
            <li class="list-group-item active">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Zawartość <span class="badge badge-light">{{ collection_items|length }}</span></h5>
                </div>
            </li>
            {% if collection_items %}
                {% for collection_item in collection_items %}
                    <li class="list-group-item">
                        <a href="{% url 'collections:item' collection_item.id %}">
                            <h5 class="mb-1">
                                {% if collection_item.collectionValue_logo %}
                                    <img class="image-small" src="{{ collection_item.collectionValue_logo.url }}">
                                {% endif %}
                                {{ collection_item.name }}
                                {% if collection_item.is_new_item %}
                                    <span class="badge badge-warning">Nowość</span>
                                {% endif %}
                            </h5>
                            <h6 class="text-muted">{{ collection_item.get_short_desc }}</h6>
                        </a>
                    </li>
                {% endfor %}
            {% else %}
                <li class="list-group-item">Kolekcja nie zawiera przedmiotów.</li>
            {% endif %}
        </div>
    </ul>
    <div class="modal fade" id="deleteConfirmation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Czy na pewno chcesz usunąć {{ collection.name }}?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                <div class="modal-body">
                    Usunięcie kolekcji jest operacją nieodwracalną. Oznacza to, że kolekcja oraz dodane do niej elementy nie będą możliwe do odzyskania po zatwierdzeniu tej operacji.
                </div>
                <div class="modal-footer">
                    <form class="form-horizontal" role="form" action="{% url 'collections:delete_collection' collection.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i>&nbsp;Usuń
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

collectionsapp/templates/collections/header.html
<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <meta charset="UTF-8"/>
    <title>{% block title %}Menedżer kolekcji{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Expanded:300,400&amp;subset=latin-ext" rel="stylesheet">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'collectionsapp/css/style.css' %}" type="text/css"/>
    <link rel="shortcut icon" href="{% static 'collectionsapp/favicon.ico' %}" type="image/png"/>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand" href="{% url 'collections:index' %}"><i class="fas fa-archive"></i>&nbsp;Menedżer kolekcji</a>

        {% block search %}
        {% endblock %}

        {% if user.is_authenticated %}
            <form class="form-inline" action="{% url 'collections:logout' %}">
                <span class="text-muted"><i class="fas fa-user"></i>&nbsp;{{ request.user.first_name }}&nbsp;{{ request.user.last_name }}&nbsp;</span>
                <button type="submit" class="btn btn-sm btn-default"><i class="fas fa-sign-out-alt"></i>&nbsp;Wyloguj</button>
            </form>
        {% else %}
            <form class="form-inline" action="{% url 'collections:login' %}">
                <button type="submit" class="btn btn-sm btn-default"><i class="fas fa-sign-in-alt"></i>&nbsp;Zaloguj</button>
            </form>
        {% endif %}
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer">
        <p>Made by Janek, Kuba and Kamil</p>
    </footer>
</body>
</html>

collectionsapp/templates/collections/index.html
{% extends "collections/header.html" %}

{% block search %}
    <form class="form-inline" role="search" method="get" action="{% url 'collections:index' %}">
        <div class="form-group">
            <input class="form-control mr-sm-2" type="search" placeholder="Szukaj albumu" aria-label="Search" name="q" value="{{ request.GET.q }}">
        </div>
        <button type="submit" class="btn btn-sm btn-light"><i class="fas fa-search"></i></button>
    </form>
{% endblock %}

{% block content %}
    <ul class="list-group">
        {% if user.is_authenticated %}
            <div class="get-away">
                <a class="btn btn-sm btn-success" href="{% url 'collections:create_collection' %}"><i class="fas fa-plus"></i>&nbsp;Dodaj&nbsp;kolekcję
                </a>
            </div>
        {% endif %}
        <div class="get-away">
            <li class="list-group-item active">
                <a href="{% url 'collections:index' %}" >
                    <h5 class="mb-1">Kolekcje&nbsp;<span class="badge badge-light">{{ collections|length }}</span></h5>
                </a>
            </li>

            {% if collections %}
                {% for collection in collections %}
                    <li class="list-group-item">
                        <a href="{% url 'collections:detail' collection.id %}">
                            <div class="d-flex justify-content-between">
                                <h5 class="mb-1">
                                    {% if collection.collection_logo %}
                                        <img class="image-small" src="{{ collection.collection_logo.url }}">
                                    {% endif %}
                                    {{ collection.name }}
                                    {% if collection.is_recently_created %}
                                        <span class="badge badge-warning">Nowość</span>
                                    {% endif %}
                                </h5>
                                <h2 class="mb-1 col-sm4">
                                    {% if user == collection.user %}
                                        <span data-toggle="tooltip" title="Ta kolekcja należy do Ciebie."><i class="fas fa-universal-access"></i></span>
                                    {% endif %}
                                </h2>
                            </div>
                            <h6 class="text-muted">{{ collection.get_short_desc }}</h6>
                        </a>
                    </li>
                {% endfor %}
            {% else %}
                <li class="list-group-item">Brak zdefiniowanych kolekcji</li>
            {% endif %}
        </div>
    </ul>
{% endblock %}

collectionsapp/templates/collections/item.html
{% extends "collections/header.html" %}

{% block content %}

    <div class="w3-panel w3-leftbar w3-border-blue">
        <div>
            <div class="col-sm8">
                {% if value.collectionValue_logo %}
                    <img class="image-size" src="{{ value.collectionValue_logo.url }}">
                {% endif %}
                <h3>{{ value.name }}</h3>
            </div>
        </div>
        <small>Dodano {{ value.added }}</small>
    </div>
    <div class="w3-panel w3-leftbar w3-border-green">
        <h5>Wytworzono {{ value.date }} przez {{ value.aggregate }}</h5>
    </div>

    <div class="w3-panel w3-border w3-round">
        <h6>{{ value.desc|linebreaks }}</h6>
    </div>

    <div class="col-sm4 get-away">
        <div class="form-inline btn-group" role="group">
            <a class="btn btn-sm btn-primary" href="{% url 'collections:detail' value.collection_id.id %}">
                <i class="fas fa-chevron-left"></i>&nbsp;Powrót do kolekcji
            </a>
            {% if user == value.collection_id.user %}
                <a class="btn btn-sm btn-warning" href="{% url 'collections:edit_item' value.id %}">
                    <i class="fas fa-edit"></i>&nbsp;Edytuj
                </a>
                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteConfirmation">
                    <i class="fas fa-trash-alt"></i>&nbsp;Usuń
                </button>
            {% endif %}
        </div>
    </div>


    <div class="modal fade" id="deleteConfirmation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Czy na pewno chcesz usunąć {{ value.name }} z&nbsp;kolekcji?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                <div class="modal-body">
                    Usunięcie elementu kolekcji jest operacją nieodwracalną. Oznacza to, że element poddany usunięciu nie będą możliwy do odzyskania po zatwierdzeniu tej operacji.
                </div>
                <div class="modal-footer">

                    <form class="form-horizontal" role="form" action="{% url 'collections:delete_item' value.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i>&nbsp;Usuń
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

collectionsapp/templates/collections/login.html
{% extends 'collections/header.html' %}

{% block content %}
    <div class="container-fluid get-away">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Logowanie</h3>
                        {% if error_message %}
                            <div class="alert alert-danger" role="alert">
                                {{ error_message }}
                            </div>
                        {% endif %}
                        <form class="form-horizontal get-away" role="form" action="{% url 'collections:login' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_username">
                                    Nazwa użytkownika:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_username" maxlength="30" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_password">
                                    Hasło:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_password" maxlength="30" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-sm btn-success">Zaloguj</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer">
                        Nie posiadasz konta? <a href="{% url 'collections:register' %}" class="font-weight-bold">Kliknij tutaj</a> aby je
                        utworzyć.
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}